name = "green29_counterexample_fc"
version = "0.1.0"
defaultTargets = ["Green29FC"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "379fc0298dc146df549e7061c3ede0353a5bb51f"

[[lean_lib]]
name = "Green29FC"
